# Generated by Django 5.2 on 2025-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_tags_article_category_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
