# Generated by Django 5.2 on 2025-04-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auhtor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auhtor',
            new_name='Author',
        ),
    ]
