# Generated by Django 5.2 on 2025-05-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_top_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='top_comment_id',
            new_name='top_level_comment_id',
        ),
    ]
