# Generated by Django 5.2 on 2025-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=221)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('position', models.CharField(max_length=221)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
